---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: spring.security.oauth2.okta
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
            plugin:
                springsecurity:
                    oauth2:
                        active: true
                        registration:
                            roleNames: ['ROLE_USER']
                        providers:
                            okta:
                                api_key: '0oahmyvboxHvn9BM00h7'
                                api_secret: '0tRAAb3FFPKUkiiGRAOpy298xNXUG_eUEdAdACVt'
                                userInfoUrl: 'https://dev-768875-admin.oktapreview.com/oauth2/default/v1/userinfo'
                                authorizeUrl: 'https://dev-768875-admin.oktapreview.com/oauth2/default/v1/authorize'
                                tokenUrl: 'https://dev-768875-admin.oktapreview.com/oauth2/default/v1/token'
                                scopes: 'email profile openid'
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
